### ISSUE TITLE
Crash when selecting Jumpluff

### ISSUE THREAD

**Issue by CloggedToaster** [DreadPirateRoberts44/Pokemon-Randbats-Generator#32]
When Jumpluff is present on a team, the follow error pops up when generating a team.

![image](https://github.com/user-attachments/assets/1521a8f6-0e56-48a6-a576-470b4968d6e8)
Uncaught runtime errors:
×
ERROR
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at generateItem (http://localhost:3000/static/js/bundle.js:184:129)
    at Module.generateMon (http://localhost:3000/static/js/bundle.js:121:16)
    at generateTeam (http://localhost:3000/static/js/bundle.js:421:69)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:12563:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:12607:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:12664:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:12678:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:16821:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:16847:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:16858:9)
ERROR
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at generateItem (http://localhost:3000/static/js/bundle.js:184:129)
    at Module.generateMon (http://localhost:3000/static/js/bundle.js:121:16)
    at generateTeam (http://localhost:3000/static/js/bundle.js:421:69)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:12563:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:12607:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:12664:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:12678:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:16821:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:16847:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:16858:9)

**Comment by CloggedToaster** [comment]
Looked into this, Jumpluff does not run any items.
A couple examples:
### Gen 9:
 - Jumpluff

### Gen 8:
 - Ninjask

### Gen 7:
 ~~- Archeops~~[^1]
 ~~- Emolga~~[^1]

[^1]: Pokemon exists in a newer generation with an item
